---
title: "R Notebook"
output: html_notebook
---

```{r}
library(monocle)
pbmc.monocle <- importCDS(pbmc)
pbmc.monocle <- estimateSizeFactors(pbmc.monocle)
pbmc.monocle <- estimateDispersions(pbmc.monocle)
pbmc.monocle <- preprocessCDS(pbmc.monocle, num_dim = 20)
pbmc.monocle <- reduceDimension(pbmc.monocle, reduction_method = 'UMAP')
pbmc.monocle <- partitionCells(pbmc.monocle)
pbmc.monocle <- learnGraph(pbmc.monocle,  RGE_method = 'SimplePPT')
plot_cell_trajectory(pbmc.monocle,
                     color_by = "cell_type2") +
                     scale_color_manual(values = cell_type_color)

reducedDimA <- reduceDimension(pbmc.monocle, method = 'DDRTree')

order <- orderCells(reducedDimA)

plot_cell_trajectory(order)
#save(pbmc.monocle, reducedDimA, order, file="2018_01_09_feng_single_cell_monocle.Robj")
```

```{r}
plot_cell_trajectory(order)
```

```{r}

marker_genes = c("Hnf4a", "Alb", "Fah", "Krt8", "Krt18", "G6pc", "Sox9", "Krt7", "Krt19", "Epcam", "Onecut1", "Afp", "Xist")
to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Hnf4a", "Alb", "Fah", "Krt8") ) )
cds_subset <- order[to_be_tested,]
plot_genes_in_pseudotime(cds_subset)

to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Krt18", "G6pc", "Sox9", "Krt7") ) )
cds_subset <- order[to_be_tested,]
plot_genes_in_pseudotime(cds_subset)


to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Krt19", "Epcam", "Onecut1", "Afp", "Xist") ) )
cds_subset <- order[to_be_tested,]
plot_genes_in_pseudotime(cds_subset)

```

```{r}

to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Hnf4a", "Alb", "Fah", "Krt8") ) )
cds_subset <- order[to_be_tested,]
plot_genes_jitter(cds_subset, grouping = "State", min_expr = 0.1)

to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Krt18", "G6pc", "Sox9", "Krt7") ) )
cds_subset <- order[to_be_tested,]
plot_genes_jitter(cds_subset, grouping = "State", min_expr = 0.1)

to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Krt19", "Epcam", "Onecut1", "Afp", "Xist") ) )
cds_subset <- order[to_be_tested,]
plot_genes_jitter(cds_subset, grouping = "State", min_expr = 0.1)

to_be_tested <- row.names(subset(fData(pbmc.monocle),
gene_short_name %in% c("Cyp7a1", "Cyp3a4") ) )
cds_subset <- order[to_be_tested,]
fData(cds_subset)
plot_genes_jitter(cds_subset, grouping = "State", min_expr = 0.1)


```
